Issue 1189 use test tld
FlowCrypt/flowcrypt-android pull request #1206
Opened 2021-04-30 14:01 UTC by DenBond7

This PR replaced 'denbond7.com' with 'flowcrypt.test'
close #1189 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

2021-04-30 14:02 UTC, DenBond7 commented
@seisvelas Please check maybe I've missed something

2021-04-30 23:09 UTC, IvanPizhenko requested changes
I think some changes can be done.

2021-05-01 07:09 UTC, tomholub commented on FlowCrypt/src/androidTest/resources/ssl/localhost-cert.pem
> +        Issuer: C=UA, ST=Debug, O=FlowCrypt, CN=flowcrypt.test/emailAddress=admin@flowcrypt.test
Agree.. :)

2021-05-01 07:12 UTC, DenBond7 commented on FlowCrypt/src/androidTest/resources/ssl/localhost-cert.pem
> +        Issuer: C=UA, ST=Debug, O=FlowCrypt, CN=flowcrypt.test/emailAddress=admin@flowcrypt.test
Got it. Will do

2021-05-03 13:34 UTC, IvanPizhenko approved these changes

2021-05-03 13:35 UTC, merged