issue #1347 Detect wrong armor checksum
FlowCrypt/flowcrypt-android pull request #1371
Opened 2021-07-28 06:07 UTC by IvanPizhenko

This PR introduces detection of the armor CRC error with help of new version of PGPainless.

close #1347

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

2021-07-28 06:26 UTC, DenBond7 approved these changes

2021-07-28 06:26 UTC, DenBond7 commented on FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
> +        ex.message?.contains("crc check failed in armored message") == true
Does `PGPainless` return exception as `IOException`? it would be better to have a predefined exception here. For now, it looks a little ugly

2021-07-28 06:28 UTC, DenBond7 commented
@IvanPizhenko it seems JUnit tests were broken. Please look at them.

2021-07-28 07:20 UTC, IvanPizhenko commented
@DenBond7 thanks for noting this, will have a look.

2021-07-28 07:49 UTC, IvanPizhenko commented
@DenBond7 that's new issue arised as result of changes in the PGPainless which we asked for, see more details in this comment https://github.com/FlowCrypt/flowcrypt-android/issues/1347#issuecomment-888092171

2021-07-28 08:27 UTC, tomholub commented
The fact out tests discovered this means they are pretty good - well done with the tests on this repo.

2021-08-05 22:43 UTC, IvanPizhenko commented
@DenBond7 I think I've got it working, please recheck.

2021-08-06 06:01 UTC, DenBond7 requested changes
Please fix `use` usage

2021-08-06 06:37 UTC, IvanPizhenko commented on FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
> +          decryptionStream.close()
There situation is more complicated. It calls close and close throws exception. Then, if I don't call close() there again, I get exception later, which returned as error: `Decryption failed: java.lang.IllegalStateException: DecryptionStream MUST be closed before the result can be accessed.`

2021-08-06 06:40 UTC, DenBond7 commented on FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
> +          decryptionStream.close()
Got it. In that case, it looks good to me

2021-08-06 06:41 UTC, DenBond7 submitted a review, later dismissed

2021-08-06 06:45 UTC, IvanPizhenko commented on FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
> +          decryptionStream.close()
I.e if I break this code into:
```kotlin
      try {
        //decryptionStream.use { it.copyTo(output) }
          try{
            println("decrypt: Copying...")
            decryptionStream.copyTo(output)
            println("decrypt: Copied")
          } finally {
            println("decrypt: Closing...")
            decryptionStream.close()
            println("decrypt: Closed")
          }
      } catch (ex: IOException) {
        println("decrypt: Exception in close")
        ...
      }
```
it prints out:
```
decrypt: Copying...
decrypt: Copied
decrypt: Closing...
decrypt: Exception in close
```

2021-08-06 06:46 UTC, IvanPizhenko commented on FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
> +          decryptionStream.close()
But second call to close() succeeds

2021-08-06 18:32 UTC, IvanPizhenko commented
@DenBond7 I can't get "Instrumentation tests(with email server)" pass in CI. Rerun few times with no luck. Any ideas how to solve/improve this?

2021-08-06 20:29 UTC, DenBond7 commented
> @DenBond7 I can't get "Instrumentation tests(with email server)" pass in CI. Rerun few times with no luck. This is not first time that it happens. Any ideas how to solve/improve this?

Please mark failed tests as @NotReadyForCI. I will look at them later.

2021-08-08 06:34 UTC, IvanPizhenko commented
Did it. Hoping this will help.

2021-08-08 10:02 UTC, DenBond7 approved these changes

2021-08-08 10:02 UTC, merged