Ip 1402 better internet address test
FlowCrypt/flowcrypt-android pull request #1404
Opened 2021-08-15 10:07 UTC by IvanPizhenko

This PR adds unit tests for the class `BetterInternetAddress`.

close #1402

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)
- Difficult to test (explain why)
- Not worth testing
- Tests will be added later (issue #...)
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

2021-08-16 07:58 UTC, DenBond7 requested changes
Please rename constants. Anyway, looks good

2021-08-16 07:58 UTC, DenBond7 commented on FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
> +    private const val maxLocalPartLength = 64
Please make it UPPER_CASE

2021-08-16 07:58 UTC, DenBond7 commented on FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
> +    private const val alphanum = "\\p{L}\\u0900-\\u097F0-9"
Please make it UPPER_CASE

2021-08-16 07:58 UTC, DenBond7 commented on FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
> +    private const val validEmail = "(?:[${alphanum}!#\$%&'*+/=?^_`{|}~-]+(?:\\.[${alphanum}!#" +
Please make it UPPER_CASE

2021-08-17 08:21 UTC, DenBond7 commented
@IvanPizhenko It seems that one test fails

![image](https://user-images.githubusercontent.com/2863246/129690601-a8418a55-f75d-4293-a641-74a71a4797ea.png)

2021-08-18 06:17 UTC, DenBond7 commented
I've checked the tests after the last changes. They were failed.

![image](https://user-images.githubusercontent.com/2863246/129847212-9d2f90a1-23b7-4a4c-a52a-3aa95c788021.png)

@IvanPizhenko  Is there expected behavior?

2021-08-18 18:26 UTC, IvanPizhenko commented
it needs to be fixed

2021-08-19 09:19 UTC, DenBond7 approved these changes

2021-08-19 09:21 UTC, DenBond7 commented
It seems we have some problems with the execution of the tests. I'm working on it.

2021-08-19 15:02 UTC, DenBond7 commented
@IvanPizhenko After merge #1415, please update the current branch and retry

2021-08-20 06:31 UTC, merged