Finished translation into Russian
FlowCrypt/flowcrypt-android pull request #1628
Opened 2021-12-29 17:00 UTC by buthed

This PR Adds Russian translation to the project.

I'm releasing the below contribution under MIT license.

issue #1546

----------------------------------

**Tests** 

Found a few flaws:
Main menu does not fit text:

![image](https://user-images.githubusercontent.com/17142699/147685363-bc238281-5d43-4e7d-aca2-73581c12965c.png)

INBOX and OUTBOX fields are missing in the file strings.xml:

![image](https://user-images.githubusercontent.com/17142699/147685800-15ad076a-a46c-4c7a-842d-f41a2e7084f3.png)
![image](https://user-images.githubusercontent.com/17142699/147685808-3db2ad3e-8769-4e1f-b6cf-f62522f70f6e.png)

2021-12-29 17:55 UTC, IvanPizhenko commented
@DenBond7 I am in progress of reviewing this. Some corrections will be required.

2021-12-29 18:14 UTC, tomholub commented
@buthed thanks for the contribution!

2021-12-29 19:18 UTC, IvanPizhenko requested changes
@buthed @DenBond7  Some changes required. Please see my comments.

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="password_quality_great">отлично</string>
отличное

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="password_quality_good">хорошо</string>
хорошее

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="hide_original_message">Скрыть исходный контент</string>
исходное сообщение

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="pref_title_http_logs">Http логи</string>
Журналы Http

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="pref_title_imap_debug">IMAP дебаг</string>
Отладка IMAP

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="password_is_incorrect">Неверная ключ-фраза, попробуйте еще раз</string>
ключевая фраза

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="please_wait_while_backup_will_be_saved">Делаем резервную копию, подождите</string>
пожалуйста подождите

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="manage_notifications">Управлять уведомлениями</string>
Управление уведомлениями

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="passphrase_purged_from_memory">Ключ-фраза очищена из памяти</string>
Ключевая фраза

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="pass_phrase_changed">Ключ-фраза успешно изменена</string>
Ключевая фраза

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="password_quality_poor">недостаточный</string>
плохое

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="processing_please_wait">Обработка, подождите&#8230;</string>
пожалуйста подождите

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="template_warning_max_total_attachments_size">Общий размер добавленных вложений не должен превышать         %1$s</string>
убрать лишние пробелы

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="password_quality_weak">слабый</string>
слабое

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="pref_title_write_api_logs_to_file">Записывать логи API в файл</string>
журналы

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="decrypt_error_current_key_cannot_open_message">Ваш текущий ключ не может открыть это сообщение. Если у вас есть другие ключи, вы должны импортировать их сейчас.</string>
вы должны -> вам следует
вы должны было бы "you must", а там "you should"  в оригинале

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="pass_phrase_is_too_weak">Ваша ключ-фраза слишком слабая</string>
ключевая фраза

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="passphrase_was_changed">Ваша ключ-фраза была изменена. Отныне новые резервные копии будут защищены заданной ключ-фразой.</string>
ключевая фраза

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="different_pass_phrases">У ваших приватных ключей разные парольные фразы</string>
закрытых ключей

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="select_stronger_pass_phrase">Пожалуйста, выберите более надежную ключ-фразу. Лучше всего сочетать от 4 до 5 необычных слов.</string>
ключевую фразу

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="provide_passphrase_to_decrypt_file">Пожалуйста, укажите ключ-фразу для расшифровки этого файла</string>
ключевую фразу

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="failed_please_try_again_later">Не удалось. Пожалуйста, повторите попытку позже</string>
Не удалось завершить операцию. 
(просто не удалось звучит как-то странно)
возможно английский вариант тоже надо исправить

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="expand_an_account_managment">Расширьте управление аккаунтом</string>
Развернуть управление аккаунтом

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="legal">Политики</string>
Юридическая информация

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="experimental">Дополнительные</string>
Экспериментальные

2021-12-29 19:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values/strings.xml
> +</resources>
should not have been changed, please revert this file.

2022-01-02 02:18 UTC, IvanPizhenko requested changes
@DenBond7 @buthed I've done a more careful review after last updates, and found more points that needs to be fixed. @buthed please make corrections and tag me and @DenBond7 when that is ready. Please pay special attention to missing newlines (`\n`) and extra quotes in some translations.

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="passphrase_purged_from_memory">Ключевая фраза очищена из памяти</string>
удалена из памяти

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="public_key_below_is_safe_to_share">"Можно делиться открытыми ключами безопасно "</string>
лишние кавычки, их нет в оригинале

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="warning">"Предупреждение: "</string>
убрать кавычки

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="decrypt_error_current_key_cannot_open_message">Ваш текущий ключ не может открыть это сообщение. Если у вас есть другие ключи, вам следует импортировать их сейчас.</string>
думаю, что лучше это перефразировать:
Если у вас есть другие ключи, импортируйте их.

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="different_pass_phrases">У ваших закрытых ключей разные парольные фразы</string>
различные ключевые фразы

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="primary_address_not_defined">Основной адрес не определен</string>
не задан

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="select_stronger_pass_phrase">Пожалуйста, выберите более надежную ключевую фразу. Лучше всего сочетать от 4 до 5 необычных слов.</string>
Лучше всего использовать сочетание 4 или 5 необычных слов.

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="reconnect_your_account">Пожалуйста, повторно подключите свою учетную запись, чтобы продолжить использование %1$s с %2$s</string>
missing EOLs

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="evaluating">Оценка…</string>
В данном случае, исходя из того где оно используется, лучше перевести как
Обработка...

2022-01-02 02:18 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="crash_the_app">Сбой приложения</string>
Искусственный сбой приложения

2022-01-03 17:16 UTC, buthed commented
@IvanPizhenko @DenBond7 
I have corrected all the points you mentioned.
Checked the code again and added any missing (\ n).
Also found that ru file was missing Plurals lines.

PS.
@IvanPizhenko sorry for the many mistakes and thanks for your careful review.

2022-01-03 17:18 UTC, IvanPizhenko commented
@buthed please see a bit more notes right in the your last commit (not a lot). when you address them, I think we are ready to merge.

2022-01-03 17:21 UTC, IvanPizhenko commented
@buthed I have one more question - the folder where translations are placed is called `values-ru-rRU`. Please note that extra `r` before `RU`. Is that correct? Shouldn't it be w/o that `r`? Also @DenBond7 what do you think of this?

2022-01-03 17:28 UTC, IvanPizhenko commented
@buthed ok, all translation notes are addressed, still my question about the folder naming

2022-01-03 17:31 UTC, buthed commented
@IvanPizhenko Done.
I do not know.
The folder was created automatically.

2022-01-03 17:33 UTC, IvanPizhenko commented
> @IvanPizhenko Done. I do not know. The folder was created automatically.

ok, then let's wait for @DenBond7 comment on this.

2022-01-05 08:25 UTC, DenBond7 commented
> @buthed I have one more question - the folder where translations are placed is called `values-ru-rRU`. Please note that extra `r` before `RU`. Is that correct? Shouldn't it be w/o that `r`? Also @DenBond7 what do you think of this?

In our case it's not correct
Please look at the following examples

Here we specify a new locale for Russian at all
![image](https://user-images.githubusercontent.com/2863246/148183916-e871378a-5215-4786-912b-0a86d4ea38ff.png)

@buthed has added a version that looks like this one

![image](https://user-images.githubusercontent.com/2863246/148184109-98cef1d6-aca3-4076-90b2-94283c00c6a5.png)

In this case the translation will be available only for Russian locale where country == Russia (Ukraine, Belarus and so on will be rejected)

P.S. Sorry for the delayed reply. Too many other tasks.

2022-01-05 08:58 UTC, DenBond7 commented
Before process with this I should review the current strings and exclude some from translation.

2022-01-05 14:28 UTC, IvanPizhenko commented
@buthed Den has marked some string as non-translatable, and this PR #1638 is merged now. Please sync your branch with upstream master and then exclude from your translations all strings marked as non-translatable in the original string list.
Please also take into account Den's comment about directory name.

2022-01-05 14:30 UTC, DenBond7 commented
@buthed @IvanPizhenko That's not all. I'm on the reviewing process.

2022-01-05 15:00 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="keys_have_different_pass_phrase">У ключей другая ключева фраза</string>
Ключи имеют разную ключевую фразу

2022-01-05 15:02 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="delete_quoted_text">Удалить выделенный текст</string>
цитируемый

2022-01-05 15:07 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="provider_faq">\n\nЧасто задаваемые вопросы о провайдере: %1$s</string>
FAQ от провайдера: %1$s

2022-01-05 15:11 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="loading_labels">Загрузка вкладок</string>
Загрузка ярлыков

2022-01-05 15:12 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="could_not_check_pass_phrase">Не удалось проверить парольную ключевую фразу</string>
Не удалось проверить ключевую фразу

2022-01-05 15:14 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="forget_passphrase">Забыл ключевую фразу</string>
Забыть ключевую фразу

2022-01-05 15:15 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="active_passphrase_session">Активная сесссия ключевой фразы</string>
сессия

2022-01-05 15:18 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="key_sha1_warning_msg">Этот ключ OpenPGP не поддерживается с сообщением: Подходящие подписи для ключа не найдены. Это может быть из-за того, что отсутствуют внутренние подписи, или п
Этот ключ OpenPGP не поддерживается. Подробности: подходящие подписи для ключа не найдены. Это может быть из-за того, что отсутствуют внутренние подписи, или подписи сделаны неправильно, или он может использовать устаревшие алгоритмы, которые больше не являются безопасными и больше не поддерживаются (например, SHA-1).

2022-01-05 15:20 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="primary_address_not_defined">Основной адрес не задан</string>
Основной адрес не определен

2022-01-05 15:22 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="manually_importing_public_keys_can_be_dangerous">Импортирование вручную открытых ключей вручную может быть опасным</string>
Импортирование открытых ключей вручную может быть опасным

2022-01-05 15:23 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="encrypted">зашифрованный</string>
зашифровано

2022-01-05 15:23 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="signed">подписан</string>
подписано

2022-01-05 15:26 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="not_signed">не подписан</string>
не подписано

2022-01-05 21:27 UTC, buthed commented on FlowCrypt/src/main/res/values-ru-rRU/strings.xml
> +    <string name="key_successfully_imported">Ключ(и) успешно импортированы</string>
Changed translation without using plurals.

2022-01-05 21:35 UTC, buthed commented
> 
So far i found one problem related to word length^
![image](https://user-images.githubusercontent.com/17142699/148292797-5d834c01-4390-4167-86b1-23ccce4653a1.png)

2022-01-05 21:37 UTC, buthed commented
> > @buthed I have one more question - the folder where translations are placed is called `values-ru-rRU`. Please note that extra `r` before `RU`. Is that correct? Shouldn't it be w/o that `r`? Also @DenBond7 what do you think of this?
> 
> In our case it's not correct Please look at the following examples
> 
> Here we specify a new locale for Russian at all ![image](https://user-images.githubusercontent.com/2863246/148183916-e871378a-5215-4786-912b-0a86d4ea38ff.png)
> 
> @buthed has added a version that looks like this one
> 
> ![image](https://user-images.githubusercontent.com/2863246/148184109-98cef1d6-aca3-4076-90b2-94283c00c6a5.png)
> 
> In this case the translation will be available only for Russian locale where country == Russia (Ukraine, Belarus and so on will be rejected)
> 
> P.S. Sorry for the delayed reply. Too many other tasks.

You're right. Rebuilt to directory for all regions.

2022-01-05 22:24 UTC, IvanPizhenko commented
@buthed 3 more things to fix after reviewing your last commit.

2022-01-05 22:57 UTC, buthed commented
@IvanPizhenko Done

2022-01-05 23:10 UTC, IvanPizhenko commented
> @IvanPizhenko Done

@buthed Thank you! So we will wait now for the final word from the @DenBond7

2022-01-06 09:22 UTC, IvanPizhenko submitted a review, later dismissed

2022-01-06 09:42 UTC, DenBond7 requested changes
Please fix a few comments. Overall, it already looks good! I will approve it after fixing.

2022-01-06 09:42 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru/strings.xml
> +    <string name="backup_as_download_hint">Это сохранит Ваши ключи в виде файла. Очень безопасный вариант, если Ваше устройство зашифровано или если Вы можете хранить этот файл в безопасности. Если В
Ваше зашифрованное
поэтому Вам

2022-01-06 09:42 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru/strings.xml
> +    <string name="password_quality_poor">плохое</string>
плохая(ключевая фраза)

2022-01-06 15:42 UTC, DenBond7 approved these changes

2022-01-06 19:18 UTC, IvanPizhenko commented
@DenBond7 CI did not run here and this does not let merging this PR normally. I believe it's because this PR comes from the external user which does not have permissions for our CI. Can you please forcemerge it? Since both of us have already approved it.

2022-01-06 19:39 UTC, merged