Issue 1193 navigation components
FlowCrypt/flowcrypt-android pull request #1712
Opened 2022-03-11 14:27 UTC by DenBond7

This PR did the migration to Navigation components over the whole app and other important architecture changes

close #1193
close #1274
close #1709
close #1192

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

2022-04-11 13:24 UTC, DenBond7 commented
> When do you think this one could be ready? I'll be writing an issue that I think could be worked on after this one merges.

I'm on the final touches. I'm working on fixing tests. I hope it will be done this week.

2022-04-15 21:51 UTC, IvanPizhenko requested changes
@DenBond7 some minor comments below.

2022-04-15 21:51 UTC, IvanPizhenko commented on FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseFragment.kt
> +
is it intentionally empty? If so, please put a comment like `// nothing to do here`

2022-04-15 21:51 UTC, IvanPizhenko commented on FlowCrypt/src/main/res/values-ru/strings.xml
> +    <string name="import_keys_from_different_sources">Вы пытаетесь импортировать ключи с разных источников</string>
maybe "из разных"?

2022-04-16 08:31 UTC, DenBond7 commented on FlowCrypt/src/main/res/values-ru/strings.xml
> +    <string name="import_keys_from_different_sources">Вы пытаетесь импортировать ключи с разных источников</string>
good one. Thanks!

2022-04-16 21:10 UTC, IvanPizhenko approved these changes

2022-04-17 06:00 UTC, merged